packages:
  - apps/*
  - packages/*
ignoredBuiltDependencies:
  - msgpackr-extract
onlyBuiltDependencies:
  - '@clerk/shared'
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma
  - sharp
